### ISSUE TITLE
Missing publishing year and translator info from colophon

### ISSUE THREAD

**Issue by robinwhittleton** [michael-77/victor-hugo_les-miserables_isabel-f-hapgood#1]
See for example https://github.com/standardebooks/emile-gaboriau_monsieur-lecoq_laura-e-kendall/blob/c6e8e4e1b0dc3f0bbfc9fc6625d58518cf183609/src/epub/text/colophon.xhtml#L14-L18 .

**Comment by michael-77** [comment]
Resolved in 6a28807
