### ISSUE TITLE
Potentially problematic mismatched diacritics

### ISSUE THREAD

**Issue by robinwhittleton** [michael-77/victor-hugo_les-miserables_isabel-f-hapgood#3]
Running `se find-mismatched-diacritics .` shows a bunch of places where there are both a word with accents and without. There are some obvious false positives, but could you investigate to see if any are a real problem?

**Comment by michael-77** [comment]
There are loads and its mainly sections in French or proper names which have the same word appearing elsewhere in English without accents.
I went through and corrected them in 217d52b31f841bc1e733059a890a98d8b4e2f27a during the production process - I was very thankful for the tool!
