### ISSUE TITLE
Banknote should be a traced SVG

### ISSUE THREAD

**Issue by robinwhittleton** [michael-77/victor-hugo_les-miserables_isabel-f-hapgood#5]
We want images to be vectors by default so that we can support dark mode in readers with that functionality. Can you convert this bank note? We don’t have instructions written up in the manual but there’s processes on the mailing list. You can look at my recent Babbage book for an example, but typically I:

- Include the original scan in the images folder (e.g. https://github.com/standardebooks/charles-babbage_passages-from-the-life-of-a-philosopher/blob/master/images/frontispiece.source.png)
- Convert that to pure (or nearly pure) black and white in an image editor (e.g. https://github.com/standardebooks/charles-babbage_passages-from-the-life-of-a-philosopher/blob/master/images/frontispiece.png)
- Run that through Inkscape’s tracer, save and optimise the SVG and drop it in the src/epub/images folder (e.g. https://github.com/standardebooks/charles-babbage_passages-from-the-life-of-a-philosopher/blob/master/src/epub/images/frontispiece.svg). Unfortunately that step contains a multitude of smaller steps, especially with optimisation, but I can maybe help with that if needed. This is probably going to take a couple of back and forths.
- Finally, include with alt text and an appropriate `epub:type` (e.g. https://github.com/standardebooks/charles-babbage_passages-from-the-life-of-a-philosopher/blob/master/src/epub/text/frontispiece.xhtml#L11)

**Comment by michael-77** [comment]
OK, I think I've managed to do this and make it smaller.
Would you mind having a look at https://github.com/michael-77/victor-hugo_les-miserables_isabel-f-hapgood/commit/fbbc3c1fec837f11ac8aae236350b0a8b120ec8e to see what you think?
The svg itself is at https://github.com/michael-77/victor-hugo_les-miserables_isabel-f-hapgood/blob/master/src/epub/images/banknote.svg
Many thanks
Michael

**Comment by robinwhittleton** [comment]
Looks good to me :)
