### ISSUE TITLE
Jeune Malade should be marked up as a poem

### ISSUE THREAD

**Issue by robinwhittleton** [michael-77/victor-hugo_les-miserables_isabel-f-hapgood#9]
At the moment it’s just quoted.

**Comment by michael-77** [comment]
I didn't consider this one to be a "long poem" hence just quoting it but happy to change it.

**Comment by robinwhittleton** [comment]
Ah, OK. @acabal?

**Comment by michael-77** [comment]
For reference:

https://github.com/michael-77/victor-hugo_les-miserables_isabel-f-hapgood/blob/bb6e923ae8ab8ff596e9826d991e4bd151f5e8b7/src/epub/text/chapter-5-5-3.xhtml#L40

**Comment by acabal** [comment]
Correct, short poems are quoted not italicized: https://standardebooks.org/contribute/typography#names-and-titles

Long/epic poems are italicized, like the Iliad, etc.
